# Generated by Django 3.0.1 on 2019-12-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myChart', '0002_patients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
