# Generated by Django 3.0.1 on 2020-04-18 08:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frigde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fg_name', models.CharField(default='frigde_1', max_length=30)),
                ('storage_date', models.DateField(default=django.utils.timezone.now)),
                ('storage_temp', models.CharField(choices=[('fridge', 'less than 40'), ('freezer', '0')], default='fridge', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('waste_id', models.AutoField(primary_key=True, serialize=False)),
                ('waste_name', models.CharField(default='home', max_length=20)),
                ('qty_recorded', models.PositiveIntegerField(default=0)),
                ('waste_type', models.CharField(choices=[('compost', 'compost'), ('recycle', 'recycle'), ('trash', 'trash')], default='compost', max_length=20)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('budget', models.IntegerField(default=0)),
                ('foods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, null=True, size=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('expiration_date', models.DateField(null=True)),
                ('food_type', models.CharField(choices=[('meat', 'meat'), ('poletrie', 'poletrie'), ('vegetable', 'vegetable'), ('fruit', 'fruit'), ('dairy', 'dairy'), ('other', 'other')], default='other', max_length=20)),
                ('item_description', models.CharField(max_length=30, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('fridge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WasteManagement.Frigde')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
