# Generated by Django 3.0.1 on 2020-01-09 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('waste_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('waste_name', models.CharField(default='home', max_length=20)),
                ('qty_recorded', models.PositiveIntegerField(default=0)),
                ('waste_type', models.CharField(choices=[('compost', 'compost'), ('recycle', 'recycle'), ('trash', 'trash')], default='compost', max_length=20)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
